- name: Check variables
  fail:
    msg: "manifests is not set."
  when: not manifests

- name: Apply K8s Changes
  block:
  - name: Create tmp folder
    file:
      path: ./tmp
      state: directory

  - name: Generate manifests
    template:
      src: "templates/{{ item }}.yml.j2"
      dest: "./tmp/{{ item }}.yml"
    with_items:
      - "{{ manifests }}"

  - name: deploy items
    command: >-
      kubectl apply -f tmp/{{ item }}.yml --record
    changed_when: "'created' in deploy_output.stdout or 'configured' in deploy_output.stdout"
    register: deploy_output
    with_items:
      - "{{ manifests }}"
  always:
    - name: Cleanup template files
      file:
        path: "tmp"
        state: absent

