# https://dev.to/musabhusaini/remote-development-with-multi-node-microk8s-cluster-and-scaffold-4o1d

- name: install MicroK8s
  snap:
    name: microk8s
    state: present
    classic: true
  become: true

- name: wait for MicroK8s to be ready
  command: microk8s status --wait-ready
  register: wait_result
  failed_when: "'microk8s is running' not in wait_result.stdout"
  retries: 20
  delay: 3
  become: true

- name: add kubectl alias
  command: snap alias microk8s.kubectl kubectl
  become: true

- name: enabling microk8s modules
  command: >-
    /snap/bin/microk8s enable {{ item }}
  changed_when: "'Enabling' in enabling_results.stdout"
  register: enabling_results
  with_items:
  - dns
  - ingress 
  - storage

# Configuring Local Storage
- name: get local hostpath-provisioner deploy in kube-system
  command: /snap/bin/microk8s kubectl get -o yaml -n kube-system deploy hostpath-provisioner
  register: hostpath_provisioner
  when: configure_local_storage

- name: Creating tmp folder
  file:
    name: tmp
    state: directory

- name: write hostpath_provisioner new deploy file
  copy:
    content: "{{ new_deploy }} "
    dest: tmp/hostpath_provisioner_new_deploy.yml
  vars:
    old_path: /var/snap/microk8s/common/default-storage
    new_path: /data/snap/microk8s/common/default-storage
    new_deploy: "{{ hostpath_provisioner.stdout | replace(old_path, new_path) }}"
  become: true
  when: configure_local_storage

- name: apply hostpath_provisioner
  command: /snap/bin/microk8s kubectl apply -f tmp/hostpath_provisioner_new_deploy.yml
  when: configure_local_storage

- name: stopping microk8s
  command: /snap/bin/microk8s stop
  register: cmd_res
  retries: 5
  until: "'Stopped.' in cmd_res.stdout"
  when: configure_local_storage

- name: restart microk8s
  command: /snap/bin/microk8s start
  register: cmd_res
  retries: 5
  until: "'Started.' in cmd_res.stdout"
  when: configure_local_storage

# Configuring NFS Storage
- name: Adding NFS package
  apt:
    name: nfs-common
    state: present
  become: true

- name: create .kube folder
  file:
    path: ~/.kube
    state: directory

- name: generate kubeconfig
  shell: >-
    /snap/bin/microk8s kubectl config view --raw > $HOME/.kube/config

- name: Cleanup
  file: 
    name: tmp
    state: absent