---
- hosts: "{{ target_host | default('all') }}"
  remote_user: "{{ remote_user | default('ubuntu') }}"
  become: true
  
  roles:
  - create_ansible_user
  
  handlers:
  - name: restart ssh
    ansible.builtin.service:
      name: sshd
      state: restarted
