---
- hosts: 
  - k8s-master
  - microk8s-cluster-node-01
  remote_user: ansible
  
  roles:
    - microk8s_setup
    - include_role:
      name: metallb_setup
      when: add_bare_metal_load_balancer