---
- hosts: localhost
  
  tasks: 
  - name: Deploy pihole
    block:
    - include_role:
        name: pihole_k8s

    always:
    - name: Cleanup template files  
      file:
        path: "{{ item }}"
        state: absent
      with_items:
        - namespace.yml
        - volumes.yml
        - pihole.yml