---
- hosts: homeserver
  remote_user: ansible
  become: true
  
  roles:
  - time_machine_server
  
  handlers:
  - name: restart netatalk service 
    service:
      name: netatalk
      state: restarted
  