apiVersion: apps/v1
kind: Deployment
metadata:
  name: time-machine
  labels:
    app: time-machine
  namespace: file-sharing
spec:
  selector:
    matchLabels:
      app: time-machine
  template:
    metadata:
      labels:
        app: time-machine
    spec:
      containers:
      - name: time-machine
        image: odarriba/timemachine
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 548
          hostPort: 548
        - containerPort: 636
          hostPort: 636
        # volumeMounts:
        # - name: time-machine-volume-mount
        #   mountPath: /mnt/exthdd/timemachine
