---
nfs:
  server_ip: 192.168.0.225
  base_path: /mnt/storage0/k8svolumes

# Ansible itself related variable
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
user_ansible_keys:
  public: "{{ vault_user_ansible_keys.public }}"
  private_key: "{{ vault_user_ansible_keys.private_key }}"

# Pihole
pihole_web_password: "{{ vault_pihole_web_password }}"

# Time Machine
time_machine_passsword: "{{ vault_time_machine_passsword }}"

## MicroK8s Cluster
k8s_cluster:
  certificate_authority_data: "{{ vault_k8s_cluster.certificate_authority_data }}"
  client_certificate_data: "{{ vault_k8s_cluster.client_certificate_data }}"
  client_key_data: "{{ vault_k8s_cluster.client_key_data }}"
  token: "{{ vault_k8s_cluster.token }}"
  ip: 192.169.0.56

# NordVpn
nordvpn_username: "{{ vault_nordvpn_username }}"
nordvpn_password: "{{ vault_nordvpn_password }}"

# Plex
plex_claim: "{{ vault_plex_claim }}"

# Code Server
code_server_sudo_password: "{{ vault_code_server_sudo_password }}"
code_server_login_password: "{{ vault_code_server_login_password }}"

# Databases
databases: "{{ vault_databases }}"