---
# Ansible itself related variable
ansible_sudo_pass: "{{ vault_ansible_sudo_pass }}"
user_ansible_keys:
  public: "{{ vault_user_ansible_keys.public }}"
  private_key: "{{ vault_user_ansible_keys.private_key }}"

# Pihole
pihole_web_password: "{{ vault_pihole_web_password }}"
