k8s_cluster_master_ip: 192.168.0.56
load_balancer_ip: 192.168.0.64

dns_provider: cloudflare
dns_providers:
  cloudflare:
    primary: 1.1.1.1
    secondary: 1.1.0.0
  google:
    primary: 8.8.8.8
    secondary: 4.4.4.4

pihole_base: "/mnt/data/pihole"

container:
  cpu: 0.2
  memory: 128M
  memory_swap: 128M

stand_up_retries: 60

namespace: network-services
nfs_server_ip: 192.168.0.225
nfs_mount_path: /mnt/storage0/k8svolumes/pihole
