---
apiVersion: v1
kind: ConfigMap
metadata:
  name: plex-cm
  labels:
    app: plex
data:
  PLEX_ADVERTISE_IP: http://192.168.0.65:32400/,https://plex.casa.com/

---
apiVersion: v1
data:
 PLEX_CLAIM_VALUE: Y2xhaW0tQUVadU5zczlWNmdyalhOUGpKSFc=
kind: Secret
metadata:
 name: plex-secrets
 namespace: applications
type: Opaque

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: plex-pv
  namespace: applications
  labels:
    location: truenas
spec:
  storageClassName: nfs
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  mountOptions:
    - hard
    # - rw
    # - sync
    # - no_subtree_check
    # - no_root_squash
    - nfsvers=4
  nfs:
    server: 192.168.0.225
    path: "/mnt/storage0/arquivos/Plex"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plex-pvc
  namespace: applications
  labels:
    app: plex
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex
  namespace: applications
spec:
  selector:
    matchLabels:
      app: plex
  template:
    metadata:
      labels:
        app: plex
    spec:
      hostNetwork: true
      containers:
      - name: plex-container
        image: linuxserver/plex
        imagePullPolicy: Always
        # resources:
        #   limits:
        #     memory: "2Gi"
        #     cpu: "4000m"
        env: 
        - name: VERSION
          value: docker
        - name: PUID
          value: "1002"
        - name: PGID
          value: "1004"
        - name: PLEX_CLAIM
          valueFrom: 
            secretKeyRef:
              name: plex-secrets
              key: PLEX_CLAIM_VALUE
        - name: UMASK_SET
          value: "022"
        - name: ADVERTISE_IP
          valueFrom:
            configMapKeyRef:
              name: plex-cm
              key: PLEX_ADVERTISE_IP
        ports:
        # TCP PORTS
        - containerPort: 3005
        - containerPort: 8324
        - containerPort: 32400
        - containerPort: 32469
        # UDP PORTS
        - containerPort: 1900
          protocol: UDP
        - containerPort: 5353
          protocol: UDP
        - containerPort: 32410
          protocol: UDP
        - containerPort: 32412
          protocol: UDP
        - containerPort: 32413
          protocol: UDP
        - containerPort: 32414
          protocol: UDP
        volumeMounts:
          - name: config-volume
            mountPath: /config
          - name: media-volume
            mountPath: /media
      volumes:
        - name: config-volume
          nfs:
            server: 192.168.0.225
            path: "/mnt/storage0/arquivos/Plex/config"
            # server: {{ nfs_server_ip }}
            # path: "{{ nfs_mount_path }}/etc-pihole"
        - name: media-volume
          persistentVolumeClaim:
            claimName: plex-pvc
          # nfs:
          #   server: 192.168.0.225
          #   path: "/mnt/storage0/arquivos/Plex/movies"
            # server: {{ nfs_server_ip }}
            # path: "{{ nfs_mount_path }}/etc-pihole"
---
kind: Service
apiVersion: v1
metadata:
  name:  plex-svc-tcp
  namespace: applications
  annotations:
    metallb.universe.tf/allow-shared-ip: plex_shared_dns
spec:
  selector:
    app:  plex
  type:  LoadBalancer
  loadBalancerIP: 192.168.0.65
  ports:
  - name: tcp-3005
    port: 3005
    targetPort: 3005
  - name: tcp-8324
    port: 8324
    targetPort: 8324
  - name: tcp-32400
    port: 32400
    targetPort:  32400
  - name: tcp-32469
    port: 32469
    targetPort: 32469
---
kind: Service
apiVersion: v1
metadata:
  name:  plex-svc-udp
  namespace: applications
  annotations:
    metallb.universe.tf/allow-shared-ip: plex_shared_dns
spec:
  selector:
    app:  plex
  type:  LoadBalancer
  loadBalancerIP: 192.168.0.65
  # loadBalancerIP: {{ load_balancer_ip }}
  ports:
  - name: udp-1900
    port: 1900
    targetPort: 1900
    protocol: UDP
  - name: udp-5353
    port: 5353
    targetPort: 5353
    protocol: UDP
  - name: udp-32410
    port: 32410
    targetPort: 32410
    protocol: UDP
  - name: udp-32412
    port: 32412
    targetPort: 32412
    protocol: UDP
  - name: udp-32413
    port: 32413
    targetPort: 32413
    protocol: UDP
  - name: udp-32414
    port: 32414
    targetPort: 32414
    protocol: UDP