- name: Install docker
  shell: curl -sSL get.docker.com | sh

- name: Add ansible user to docker group
  user:
    name: ansible
    groups: 
    - docker
    append: yes

- name: Set Docker daemon options
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Enable routing
  replace:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'

- name: Rebooting host
  reboot:
    msg: Rebooting host