- name: iDrive Setup
  block:
  - name: Get kubeconfig file
    template:
      src: templates/kubeconfig.j2
      dest: tmp/k8s-kubeconfig.yml

- name: Deploy 
  
  always:
  - name: Cleanup
    file:
      path: tmp
      state: absent