# Instruction from https://wiki.learnlinux.tv/index.php/Setting_up_a_Raspberry_Pi_Kubernetes_Cluster_with_Ubuntu_20.04

- name: Enable cgroup via boot commandline if not already enabled for Ubuntu on a Raspberry Pi
  lineinfile:
    path: /boot/firmware/cmdline.txt
    backrefs: yes
    regexp: '^((?!.*\bcgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1\b).*)$'
    line: '\1 cgroup_enable=cpuset cgroup_enable=memory cgroup_memory=1 swapaccount=1'

- name: Update Ubuntu
  apt:
    name: nfs-common
    update_cache: yes
    upgrade: dist
  notify: reboot

- name: Install docker
  shell: curl -sSL get.docker.com | sh

- name: Add ansible user to docker group
  user:
    name: ansible
    groups: 
    - docker
    append: yes

- name: Set Docker daemon options
  copy:
    src: files/daemon.json
    dest: /etc/docker/daemon.json

- name: Enable routing
  replace:
    path: /etc/sysctl.conf
    regexp: '#net.ipv4.ip_forward=1'
    replace: 'net.ipv4.ip_forward=1'
  notify: reboot

- name: Check docker daemon
  systemd:
    state: started
    name: docker

- name: Add Kubernetes repository
  lineinfile:
    path: /etc/apt/sources.list.d/kubernetes.list
    line: "deb http://apt.kubernetes.io/ kubernetes-xenial main"
    create: true
    state: present

- name: Add the GPG key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
    state: present

- name: Install required Kubernetes packages
  apt:
    name: "{{ item }}"
    update_cache: true
    state: present
  with_items:
  - kubeadm
  - kubectl
  - kubelet