--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins-container
        image: jenkins/jenkins:lts
        ports:
          - name: http-port
            containerPort: 8080
          - name: jnlp-port
            containerPort: 50000
        volumeMounts:
          - name: jenkins-vol
            mountPath: /var/jenkins_vol
        # resources:
        #   requests:
        #     cpu: 1000m
        #     memory: 1024Gi
        #   limits:
        #     cpu: 4000m
        #     memory: 4098Gi
      volumes:
        - name: jenkins-vol
          emptyDir: {}