---
apiVersion: v1
kind: Service
metadata:
  name: jenkins
  namespace: jenkins
  annotations:
    metallb.universe.tf/address-pool: microk8s-ip-space
spec:
  type: LoadBalancer
  ports:
    - name: ui
      port: 80
      targetPort: 8080
    - name: jnlp
      port: 50000
      targetPort: 50000
  selector:
    app: jenkins
  externalTrafficPolicy: Local
