apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv
  namespace: jenkins
spec:
  storageClassName: jenkins-pv
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 20Gi
  persistentVolumeReclaimPolicy: Retain
  # hostPath:
  #   path: /data/jenkins-volume/
  mountOptions:
    - hard
    - nfsvers=4
  nfs:
    server: 192.168.0.225
    path: "/mnt/storage0/k8svolumes/jenkins"
    # server: {{ nfs_server_ip }}
    # path: "{{ nfs_mount_path }}/etc-pihole"