---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-local-volume-1
  labels:
    location: local
    app: pihole
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pihole/etc-pihole"

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-local-volume-2
  labels:
    location: local
    app: pihole
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/pihole/etc-dnsmasq.d"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pv-claim-pihole
  labels:
    app: pihole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pv-claim-dnsmasq
  labels:
    app: pihole
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 4Gi