- name: Create Groups
  group:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_user_groups }}"

- name: Create user and groups
  user:
    name: "{{ ansible_user_name }}"
    group: adm
    groups: "{{ ansible_user_groups }}"
    shell: /bin/bash

- name: Add "{{ ansible_user_name }}" user to the sudoers
  copy:
    dest: "/etc/sudoers.d/{{ ansible_user_name }}"
    content: "{{ ansible_user_name }}  ALL=(ALL)  NOPASSWD: ALL"

- name: Deploy SSH Key
  authorized_key: 
    user: "{{ ansible_user_name }}"
    key: "{{ user_ansible_keys.public }} "
    state: present
  
- name: Disable Password Authentication
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    backup: yes

- name: Disable Root Login
  lineinfile:
    dest: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    backup: yes

- name: restart ssh
  service:
    name: sshd
    state: restarted
