- name: Creat tmp folder
  file:
    name: tmp_volume
    state: directory

- name: Template files
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "tmp_volume/{{ item }}.yml"
  with_items:
  - users-pvc
  - users-pv

- name: Deploy PV's
  command: >-
    kubectl apply -f tmp_volume/{{ item }}.yml --record
  changed_when: "'created' in deploy_pv_output.stdout or 'configured' in deploy_pv_output.stdout"
  register: deploy_pv_output
  with_items:
  - users-pv

- name: Deploy PVC's
  command: >-
    kubectl apply -f tmp_volume/{{ item }}.yml --record
  changed_when: "'created' in deploy_pvc_output.stdout or 'configured' in deploy_pvc_output.stdout"
  register: deploy_pvc_output
  with_items:
  - users-pvc

- name: Remove tmp_volume folder
  file:
    name: tmp_volume
    state: absent