- name: Creat tmp folder
  file:
    name: tmp
    state: directory

- name: Template the K8S config files
  template:
    src: "templates/{{ item }}.yml.j2"
    dest: "tmp/{{ item }}.yml"
    mode: "0444"
  with_items:
  - namespace
  - volumes
  - pihole

- name: deploy items
  command: >-
    kubectl apply -f tmp/{{ item }}.yml --record
  changed_when: "'configured' in deploy_output.stdout"
  register: deploy_output
  with_items:
  - namespace
  - volumes
  - pihole

- name: Check rollout
  include_role:
    name: k8s_check_rollout
  vars:
    k8_deployment_name: pihole
    k8_namespace: network-services
    retries: 30
    delay: 10