plex_namespace: applications
nfs_server_ip: 192.168.0.225
nfs_mount_path: /mnt/storage0/arquivos/Plex
plex_advertise_ip: http://192.168.0.65:32400/,https://plex.casa.com/
plex_image: gpoleze/pms:arm64
resources:
  min:
    cpu: "20m"
    memory: "256Mi"
  max:
    cpu: "2000m"
    memory: "2Gi"
plex_uid: 1002
plex_gid: 1004
plex_timezone: America/Vancouver
plex_extra_ports:
  tcp:
  - { number: 3005, name: "plex-home-theater" }
  - { number: 8324, name: "plex-for-roku" }
  - { number: 32469, name: "plex-DLNA-TCP" }
  udp:
  - { number: 1900, name: "plex-DLNA-UDP" }
  - { number: 5353, name: "Bonjour-Avahi " }
  - { number: 32410, name: "GDM-Network-Discovery-1" }
  - { number: 32412, name: "GDM-Network-Discovery-2" }
  - { number: 32413, name: "GDM-Network-Discovery-3" }
  - { number: 32414, name: "GDM-Network-Discovery-4" }