- name: Stop Ubuntu DNS Server (systemd-resolved.service)
  # command: systemctl stop systemd-resolved.service
  service:
    name: systemd-resolved
    state: stopped

- name: Disable Ubuntu DNS Server (systemd-resolved.service)
  command: systemctl disable systemd-resolved.service
    
- name: Update resolv.conf file to have a static DNS server other than the default one
  template:
    src: templates/resolv.conf.j2
    dest: /etc/resolv.conf
    mode: "0644"

- name: Add pihole script
  template:
    src: templates/pihole.sh.j2
    dest: /usr/local/bin/pihole.sh
    owner: root
    group: homeserver
    mode: "0554"

- name: Add pihole_stop script
  copy:
    src: files/pihole_stop.sh
    dest: /usr/local/bin/pihole_stop.sh
    owner: root
    group: homeserver
    mode: "0554"
    

- name: stopping possible running container
  command: pihole_stop.sh
  ignore_errors: yes

- name: Execute script and start the server
  shell: pihole.sh

  